---
name: typescript-styled-plugin
description: typescript-styled-plugin
homepage: https://github.com/styled-components/typescript-styled-plugin
licenses:
  - MIT
languages:
  - TypeScript
categories:
  - LSP

source:
  id: pkg:npm/@styled/typescript-styled-plugin@1.0.1
  extra_packages:
  - typescript

bin:
  typescript-styled-plugin: node:lib/index.js
