local M = {}

local ADJECTIVES = {
  'adamant',
  'adept',
  'adventurous',
  'arcadian',
  'auspicious',
  'awesome',
  'blossoming',
  'brave',
  'charming',
  'chatty',
  'circular',
  'considerate',
  'cubic',
  'curious',
  'delighted',
  'didactic',
  'diligent',
  'effulgent',
  'erudite',
  'excellent',
  'exquisite',
  'fabulous',
  'fascinating',
  'friendly',
  'glowing',
  'gracious',
  'gregarious',
  'hopeful',
  'implacable',
  'inventive',
  'joyous',
  'judicious',
  'jumping',
  'kind',
  'likable',
  'loyal',
  'lucky',
  'marvellous',
  'mellifluous',
  'nautical',
  'oblong',
  'outstanding',
  'polished',
  'polite',
  'profound',
  'quadratic',
  'quiet',
  'rectangular',
  'remarkable',
  'rusty',
  'sensible',
  'sincere',
  'sparkling',
  'splendid',
  'stellar',
  'tenacious',
  'tremendous',
  'triangular',
  'undulating',
  'unflappable',
  'unique',
  'verdant',
  'vitreous',
  'wise',
  'zippy',
}

local NOUNS = {
  'aardvark',
  'accordion',
  'apple',
  'apricot',
  'bee',
  'brachiosaur',
  'cactus',
  'capsicum',
  'clarinet',
  'cowbell',
  'crab',
  'cuckoo',
  'cymbal',
  'diplodocus',
  'donkey',
  'drum',
  'duck',
  'echidna',
  'elephant',
  'foxglove',
  'galaxy',
  'glockenspiel',
  'goose',
  'hill',
  'horse',
  'iguanadon',
  'jellyfish',
  'kangaroo',
  'lake',
  'lemon',
  'lemur',
  'magpie',
  'megalodon',
  'mountain',
  'mouse',
  'muskrat',
  'newt',
  'oboe',
  'ocelot',
  'orange',
  'panda',
  'peach',
  'pepper',
  'petunia',
  'pheasant',
  'piano',
  'pigeon',
  'platypus',
  'quasar',
  'rhinoceros',
  'river',
  'rustacean',
  'salamander',
  'sitar',
  'stegosaurus',
  'tambourine',
  'tiger',
  'tomato',
  'triceratops',
  'ukulele',
  'viola',
  'weasel',
  'xylophone',
  'yak',
  'zebra',
}

function M.generate_random_phrase()
  math.randomseed(os.time())

  local random_adj = ADJECTIVES[math.random(#ADJECTIVES)]
  local random_noun = NOUNS[math.random(#NOUNS)]

  local charset = 'abcdefghijklmnopqrstuvwxyz0123456789'
  local charset_len = #charset
  local random_suffix_tbl = {}
  for _ = 1, 6 do
    local random_index = math.random(charset_len)
    table.insert(random_suffix_tbl, string.sub(charset, random_index, random_index))
  end
  local random_suffix = table.concat(random_suffix_tbl)

  return random_adj .. '-' .. random_noun .. '-' .. random_suffix
end

return M
