#!/usr/bin/env sh

# focus window
alt - h : yabai -m window --focus west  || yabai -m display --focus west
alt - j : yabai -m window --focus south || yabai -m display --focus south
alt - k : yabai -m window --focus north || yabai -m display --focus north
alt - l : yabai -m window --focus east  || yabai -m display --focus east

# reset window space
shift + alt - r : yabai -m space --balance

# swap window
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# resize
shift + alt - w : yabai -m window --resize top:0:-20   || yabai -m window --resize bottom:0:-20
shift + alt - s : yabai -m window --resize bottom:0:20 || yabai -m window --resize top:0:20
shift + alt - a : yabai -m window --resize left:-50:0  || yabai -m window --resize right:-50:0
shift + alt - d : yabai -m window --resize right:50:0  || yabai -m window --resize left:50:0

# toggle window fullscreen zoom
shift + alt - f : yabai -m window --toggle zoom-fullscreen
