#!/usr/bin/env sh

# open application
cmd + shift + ctrl + alt - m : open -a "Music"
cmd + shift + ctrl + alt - y : open -a "Youtube"
cmd + shift + ctrl + alt - t : open -a "Ghostty"
cmd + shift + ctrl + alt - s : open -a "Slack"
cmd + shift + ctrl + alt - c : open -a "Google Chrome"
cmd + shift + ctrl + alt - z : [ "$(SwitchAudioSource -c -t output -f json | jq -r '.uid')" = "BuiltInHeadphoneOutputDevice" ] && SwitchAudioSource -t output -u "10ACC041-0000-0000-181E-0104B53C2278" || SwitchAudioSource -t output -u "BuiltInHeadphoneOutputDevice"

# focus window
ctrl + alt - x : yabai -m window --focus recent || yabai -m display --focus recent
ctrl + alt - h : yabai -m window --focus west   || yabai -m display --focus west
ctrl + alt - j : yabai -m window --focus south  || yabai -m display --focus south
ctrl + alt - k : yabai -m window --focus north  || yabai -m display --focus north
ctrl + alt - l : yabai -m window --focus east   || yabai -m display --focus east

# reset window space
ctrl + alt - r : yabai -m space --balance

# move window
shift + ctrl + alt - h : yabai -m window --warp west
shift + ctrl + alt - j : yabai -m window --warp south
shift + ctrl + alt - k : yabai -m window --warp north
shift + ctrl + alt - l : yabai -m window --warp east

# toggle split type
ctrl + alt - t : yabai -m window --toggle split

# move window to next/prev display
ctrl + alt - n : yabai -m window --display next && yabai -m display --focus next
ctrl + alt - p : yabai -m window --display prev && yabai -m display --focus prev

# resize
ctrl + alt - w : yabai -m window --resize top:0:-50   || yabai -m window --resize bottom:0:-50
ctrl + alt - s : yabai -m window --resize bottom:0:50 || yabai -m window --resize top:0:50
ctrl + alt - a : yabai -m window --resize left:-100:0  || yabai -m window --resize right:-100:0
ctrl + alt - d : yabai -m window --resize right:100:0  || yabai -m window --resize left:100:0

# toggle window fullscreen zoom
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen
