#!/usr/bin/env sh

# open chrome
# thinking... : open -n -a "Google Chrome" --args --profile-directory="Default"

# focus window
ctrl + alt - h : yabai -m window --focus west  || yabai -m display --focus west
ctrl + alt - j : yabai -m window --focus south || yabai -m display --focus south
ctrl + alt - k : yabai -m window --focus north || yabai -m display --focus north
ctrl + alt - l : yabai -m window --focus east  || yabai -m display --focus east

# reset window space
ctrl + alt - r : yabai -m space --balance

# swap window
shift + ctrl + alt - h : yabai -m window --swap west
shift + ctrl + alt - j : yabai -m window --swap south
shift + ctrl + alt - k : yabai -m window --swap north
shift + ctrl + alt - l : yabai -m window --swap east

# move window to next/prev display
ctrl + alt - n : yabai -m window --display next && yabai -m display --focus next
ctrl + alt - p : yabai -m window --display prev && yabai -m display --focus prev

# resize
ctrl + alt - w : yabai -m window --resize top:0:-20   || yabai -m window --resize bottom:0:-20
ctrl + alt - s : yabai -m window --resize bottom:0:20 || yabai -m window --resize top:0:20
ctrl + alt - a : yabai -m window --resize left:-50:0  || yabai -m window --resize right:-50:0
ctrl + alt - d : yabai -m window --resize right:50:0  || yabai -m window --resize left:50:0

# toggle window fullscreen zoom
ctrl + alt - f : yabai -m window --toggle zoom-fullscreen
