network_access = true
model_reasoning_effort = "xhigh"
hide_agent_reasoning = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]
model = "gpt-5.4"
personality = "friendly"

web_search = "cached"

[features]
unified_exec = true
multi_agent = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

# [mcp_servers.git-daisyui]
# command = "npx"
# args = ["mcp-remote", "https://gitmcp.io/saadeghi/daisyui"]
