[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }
size = 20

[window]
padding.x = 20
padding.y = 20
decorations = "Buttonless"
opacity = 0.8
blur = false
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/zsh"
args = ["-l", "-c", "zellij"]

[env]
TERM = "xterm-256color"
