[general]
import = [
  "~/src/github.com/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"
]

[font]
# normal = { family = "HackGen35 Console NF", style = "Regular" }
normal = { family = "UDEV Gothic 35NF", style = "Regular" }
size = 20
offset.x = 0
offset.y = 1

[window]
padding.x = 10
padding.y = 0
decorations = "Buttonless"
opacity = 0.8
blur = false
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/zsh"
args = ["-l", "-c", "zellij"]

[env]
TERM = "xterm-256color"
